name: Labeler

on:
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
        - uses: nichtsfrei/actions/pr-conventional-commit-labeler@main
          with:
            configuration_toml: release_tag.toml

